let DB, selected=new Set(), current="전체";
const $=id=>document.getElementById(id);
async function loadDB(){DB={behavior:await fetch("db/behavior.json").then(r=>r.json()),paragraph:await fetch("db/paragraph.json").then(r=>r.json()),profile:await fetch("db/profile.json").then(r=>r.json())};init();}
function init(){renderTabs();renderList();renderSelected();$("search").addEventListener("input",renderList)}
function cats(){return ["전체",...new Set(DB.behavior.items.map(x=>x.category))]}
function renderTabs(){$("tabs").innerHTML="";cats().forEach(c=>{let b=document.createElement("button");b.className="tab"+(c==current?" active":"");b.textContent=c;b.onclick=()=>{current=c;renderTabs();renderList()};$("tabs").appendChild(b)})}
function renderList(){let q=$("search").value.trim();let box=$("list");box.innerHTML="";let arr=DB.behavior.items.filter(x=>(current=="전체"||x.category==current)&&(!q||[x.label,x.category,x.group,x.tags.join(" "),x.meaning].join(" ").includes(q)));let groups={};arr.forEach(x=>{let k=x.category+" · "+x.group;(groups[k]??=[]).push(x)});Object.entries(groups).forEach(([g,items])=>{let title=document.createElement("div");title.className="group";title.textContent=g;box.appendChild(title);items.forEach(x=>{let s=document.createElement("span");s.className="chip"+(selected.has(x.id)?" on":"")+(x.category=="역할"?" role":"");s.textContent=x.label;s.title=x.meaning;s.onclick=()=>{selected.has(x.id)?selected.delete(x.id):selected.add(x.id);renderList();renderSelected()};box.appendChild(s)})});if(!arr.length)box.innerHTML='<div class="group">검색 결과가 없습니다.</div>'}
function items(){return DB.behavior.items.filter(x=>selected.has(x.id))}
function renderSelected(){let box=$("selected");box.innerHTML="";let arr=items();if(!arr.length)box.innerHTML='<span class="chip">선택 없음</span>';arr.forEach(x=>{let s=document.createElement("span");s.className="chip on";s.textContent="× "+x.label;s.onclick=()=>{selected.delete(x.id);renderList();renderSelected()};box.appendChild(s)});renderProfile()}
function scores(){let sc={};items().forEach(x=>Object.entries(x.competencies).forEach(([k,v])=>sc[k]=(sc[k]||0)+v));let memo=$("memo").value.trim();DB.behavior.memoRules.forEach(r=>{if(memo.includes(r.keyword)){Object.entries(r.competencies).forEach(([k,v])=>sc[k]=(sc[k]||0)+v)}});return sc}
function top(n=7){return Object.entries(scores()).sort((a,b)=>b[1]-a[1]).slice(0,n)}
function inferProfile(comps){let out=[];DB.profile.profiles.forEach(p=>{let hit=p.competencies.filter(c=>comps.includes(c)).length;if(hit>=p.minHit)out.push(p.name)});return out.slice(0,4).length?out.slice(0,4):["성장형"]}
function renderProfile(){let t=top();let box=$("profile");if(!t.length){box.textContent="아직 선택한 행동이 없습니다.";return}let max=Math.max(...t.map(x=>x[1]),1);box.innerHTML="";t.forEach(([k,v])=>{let row=document.createElement("div");row.className="score";row.innerHTML=`<span>${k}</span><span class="bar"><span class="fill" style="width:${Math.round(v/max*100)}%"></span></span><span>${v}</span>`;box.appendChild(row)});let p=document.createElement("div");p.style.marginTop="12px";p.innerHTML="<b>학생상:</b> "+inferProfile(t.map(x=>x[0])).join(" · ");box.appendChild(p)}
function autoPick(){let memo=$("memo").value.trim();DB.behavior.memoRules.forEach(r=>{if(memo.includes(r.keyword))r.behaviorIds.forEach(id=>selected.add(id))});renderList();renderSelected()}
function clearAll(){selected.clear();$("memo").value="";$("student").value="";$("results").textContent="생성 버튼을 누르면 결과가 표시됩니다.";renderList();renderSelected()}
function byteLen(s){return new Blob([s]).size}
function pick(a,s=0){return a[(Math.floor(Math.random()*a.length)+s)%a.length]}
function bank(type, comps){let b=[];comps.forEach(([c,score])=>DB.paragraph[type].filter(x=>x.competency==c).forEach(x=>b.push({...x,score})));return b.length?b:DB.paragraph[type]}
function polish(text){text=text.replace(/\s+/g," ").trim().replace(/긍정적인 영향을 미침/g,"공동체에 안정감을 더함").replace(/\.\s*\./g,".");return text.split(/(?<=\.)\s*/).filter(Boolean).map(s=>/[.!?]$/.test(s.trim())?s.trim():s.trim()+".").join(" ")}
function makeOne(i){let comps=top(6);let role=items().filter(x=>x.category=="역할").map(x=>x.label).slice(0,2);let lead=pick(bank("lead",comps),i).text, learn=pick(bank("learning",comps),i+2).text, life=pick(bank("life",comps),i+4).text, end=pick(bank("ending",comps),i+6).text;if(role.length&&!lead.includes(role[0]))lead=role.join(" 및 ")+" 역할을 통해 "+lead;let text=polish([lead,learn,life,end].join(" "));let target=Number($("target").value);if(byteLen(text)>target+180){let parts=text.split(/(?<=\.)\s*/);while(byteLen(parts.join(" "))>target+140&&parts.length>3)parts.splice(parts.length-2,1);text=parts.join(" ")}if($("tone").value=="short"){text=text.replace(/자연스럽게/g,"").replace(/꾸준히/g,"")}return polish(text)}
function generateAll(){let box=$("results");box.innerHTML="";if(!items().length&&!$("memo").value.trim()){box.textContent="관찰 행동을 선택하거나 자유 메모를 입력해 주세요.";return}for(let i=0;i<5;i++){let text=makeOne(i);let card=document.createElement("div");card.className="card";card.innerHTML=`<div class="top"><span>추천 ${i+1} · ${byteLen(text)} byte</span><button class="copy">복사</button></div><div class="txt">${text}</div>`;card.querySelector("button").onclick=()=>{navigator.clipboard.writeText(text);alert("복사했어요.")};box.appendChild(card)}}
function refineAll(){document.querySelectorAll(".txt").forEach(x=>x.textContent=polish(x.textContent))}
loadDB();